### ISSUE TITLE
chore: Anaytics. Question 1

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#26]
### Summary 💡
Answer the assigned question including data analysis.

### Acceptance Criteria
- [x] What day of the week has more purchases?

**Comment by GabyGO2108** [comment]
Opposed to what we thought at first, and according to the data (graphics shown in the image below), the day of the week with the most purchases is Monday, closely followed by Tuesday. We also noticed that the preferred time of purchase is in the afternoon; so there is a possibility that people tend to disconnect themselves during the weekend, and most likely surf the net during their work break hours and buy. It is also interesting to see that the top three products are health_beauty, watches_gifts and bed_bath_table. Since this items tend to be small in size, and could be bought out on a whim more than of a necessity, it could fit the hypothesis that people surf the net when their breaks (could be lunch, coffee, etc). 
As the data shows, we also have evening and night buyers, which correspond to what we could call work free hours; however it is intriguing to see that most people buy during work hours. 

![image](https://user-images.githubusercontent.com/74556825/163891268-af99055a-d79d-42a4-b286-aa92256b2f14.png)

![image](https://user-images.githubusercontent.com/74556825/163891360-38ce4e4d-dccd-4c8c-a35a-87ff62a0f17c.png)



And what about the size in the orders? Well, as seen in the heat map, these don't vary that much, but people tend to make their orders bigger during the afternoon hours of Friday.

**Comment by felipesaldata** [comment]
We considered that @GabyGO2108's answer reach the Acceptance Criteriea of the issue and we got answer's source at the [EDA Notebook ](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/blob/csv_analysis/EDA.ipynb)and the [resulting figures](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/tree/csv_analysis/figures).

Proceed to close it
