### ISSUE TITLE
feat: Graph 4. Best selling time 

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#64]
### 💡 Goal

Show the best days of the week and dates for selling online.

### 🤝 Acceptance Criteria

- [x]  date with the most sales (black friday campaign) → in numbers. Total R$ revenue and date
- [ ]  days of the week that e-commerce sells the most → heat map or similar

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example

**Comment by felipesaldata** [comment]
**Solution for the first AC:**

``` python
best_selling_date = ord_Nov_17['revenue($R1000)'].idxmax()
best_selling_revenue = ord_Nov_17['revenue($R1000)'].max()
print(best_selling_date,'Total Revenue($): ',format(best_selling_revenue*1000,'.2f'))
```
Instead of print use the propel form of streamlit like st.metric()

For the second AC i don't understand if we have to make a modification of the current heatmaps availables or a new one.
![Image](https://user-images.githubusercontent.com/46731424/171900930-b1436165-e508-4544-8d03-a41939f79b96.png)

**Comment by leopensaa** [comment]
We only keep one from the originals. The heat map needs to highlight the best day and moment for selling online. 
Thank you, @felipesaldata!
