### ISSUE TITLE
chore: define ETL process to integrate scrapper, the NLP and the dashboard

### ISSUE THREAD

**Issue by elyager** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#71]

**Comment by felipesaldata** [comment]
We had a meeting on saturday and define to work with airflow in order to script continuously our datamodel and integrate the whole functionality of our project.

Having this clear, we made an update to the datamodel visualization.

We also need to modularizate our scripts and apply the best practices to integrate all the steps.
